//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.21 at 02:58:04 PM CET 
//


package org.w3._2001.xmlschema;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

public class Adapter1
    extends XmlAdapter<String, XMLGregorianCalendar>
{


    public XMLGregorianCalendar unmarshal(String value) {
        return (org.notima.idempiere.iso20022.Iso20022FileFactory.parseISODate(value));
    }

    public String marshal(XMLGregorianCalendar value) {
        return (org.notima.idempiere.iso20022.Iso20022FileFactory.printISODate(value));
    }

}
