/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LbPanel.java
 *
 * Created on 2009-jun-16, 16:10:16
 */

package org.notima.bankgiro.adempiere.form;

import java.util.List;
import java.util.SortedMap;
import java.util.Vector;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

import org.compiere.model.I_AD_Ref_List;
import org.compiere.model.Query;
import org.compiere.model.X_AD_Ref_List;
import org.compiere.model.X_AD_Reference;
import org.compiere.util.Env;
import org.notima.bankgiro.adempiere.model.MLBSettings;

/**
 *
 * @author Daniel Tamm
 */
public class LbPanel extends javax.swing.JPanel implements I_LBSettingsPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6226579082902127767L;
	private SortedMap<String, MLBSettings>      m_settings;
    private XX_LBSettingsDialog                 m_parentDialog;
    private Vector<RefListWrapper>				m_bankFileFormats;

    /**
     * Wrap the RefList class to make it work nicely in a combo box
     * 
     * @author daniel.tamm
     *
     */
    private class RefListWrapper {
    	public I_AD_Ref_List elem;
    	
    	public RefListWrapper(I_AD_Ref_List e) {
    		elem = e;
    	}
    	
    	public String toString() {
    		return elem.getName();
    	}
    	
    	public String getValue() {
    		return elem.getValue();
    	}
    }
    
    /** Creates new form LbPanel */
    public LbPanel() {
        initComponents();
    }

    public void initPanel(XX_LBSettingsDialog parent, SortedMap<String, MLBSettings> settings) {
    	m_parentDialog = parent;
    	m_settings = settings;
    	m_bankFileFormats = new Vector<RefListWrapper>();
    	
    	// Read bank list formats
    	X_AD_Reference utlBankFileFormat = new Query(Env.getCtx(), X_AD_Reference.Table_Name, X_AD_Reference.COLUMNNAME_Name + "=?", null)
    						.setParameters(new Object[]{"utl_bankfileformat"})
    						.first();
    	
    	if (utlBankFileFormat!=null) {
    		List<X_AD_Ref_List> items = new Query(Env.getCtx(), X_AD_Ref_List.Table_Name, "AD_Reference_ID=?", null)
    						.setParameters(new Object[]{utlBankFileFormat.get_ID()})
    						.list();
    		for (X_AD_Ref_List i : items) {
    			m_bankFileFormats.add(new RefListWrapper(i));
    		}
    	}
    	ComboBoxModel model = new DefaultComboBoxModel(m_bankFileFormats);
    	utlFormatCombo.setModel(model);
    	
    }
    
    @Override
    public void getForm() {
        MLBSettings.setSetting(MLBSettings.LB_OUTPUT_DIR, directoryText.getText());
        MLBSettings.setSetting(MLBSettings.LB_FILE_NAME, fileNameText.getText());
        MLBSettings.setSetting(MLBSettings.LB_ADD_TS, addTimeToFileCheck.isSelected() ? "Y" : "N");
        MLBSettings.setSetting(MLBSettings.LB_FILE_SUFFIX, fileSuffixText.getText());
        MLBSettings.setSetting(MLBSettings.LB_RECONCILIATION_DIR, defaultDirText.getText());
        MLBSettings.setSetting(MLBSettings.LB_RECONCILIATION_MOVETO_DIR, archiveDirText.getText());
        RefListWrapper item = (RefListWrapper)utlFormatCombo.getSelectedItem();
        String utlFmt = item!=null ? item.getValue() : "";
        MLBSettings.setSetting(MLBSettings.LB_UTL_FMT, utlFmt);
    }

    @Override
    public void setForm() {

        MLBSettings outputDir = m_settings.get(MLBSettings.LB_OUTPUT_DIR);
        directoryText.setText(outputDir!=null ? outputDir.getName() : "");
        MLBSettings fileName = m_settings.get(MLBSettings.LB_FILE_NAME);
        fileNameText.setText(fileName!=null ? fileName.getName() : "BGDATA");
        MLBSettings addTime = m_settings.get(MLBSettings.LB_ADD_TS);
        addTimeToFileCheck.setSelected(addTime!=null && "Y".equalsIgnoreCase(addTime.getName()));
        MLBSettings fileSuffix = m_settings.get(MLBSettings.LB_FILE_SUFFIX);
        fileSuffixText.setText(fileSuffix!=null ? fileSuffix.getName() : "IN");

        MLBSettings defaultDir = m_settings.get(MLBSettings.LB_RECONCILIATION_DIR);
        defaultDirText.setText(defaultDir!=null ? defaultDir.getName() : "");
        MLBSettings archiveDir = m_settings.get(MLBSettings.LB_RECONCILIATION_MOVETO_DIR);
        archiveDirText.setText(archiveDir!=null ? archiveDir.getName() : "");
        MLBSettings utlFmt = m_settings.get(MLBSettings.LB_UTL_FMT);
        RefListWrapper item = null;
        for (int i=0; utlFmt!=null && i<m_bankFileFormats.size(); i++) {
        	if (m_bankFileFormats.get(i).getValue().equals(utlFmt.getName())) {
        		item = m_bankFileFormats.get(i);
        		break;
        	}
        }
        utlFormatCombo.setSelectedItem(item);

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        createFilePanel = new javax.swing.JPanel();
        directoryLabel = new javax.swing.JLabel();
        directoryText = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        fileNameText = new javax.swing.JTextField();
        addTimeToFileCheck = new javax.swing.JCheckBox();
        fileSuffixLabel = new javax.swing.JLabel();
        fileSuffixText = new javax.swing.JTextField();
        utlFormatLabel = new javax.swing.JLabel();
        utlFormatCombo = new javax.swing.JComboBox();
        readFilesPanel = new javax.swing.JPanel();
        defaultDirLabel = new javax.swing.JLabel();
        defaultDirText = new javax.swing.JTextField();
        browseDefaultDirButton = new javax.swing.JButton();
        archiveDirLabel = new javax.swing.JLabel();
        archiveDirText = new javax.swing.JTextField();
        browseArchiveDirButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 320));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        createFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create LB-files"));
        createFilePanel.setMinimumSize(new java.awt.Dimension(200, 50));
        createFilePanel.setLayout(new java.awt.GridBagLayout());

        directoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        directoryLabel.setText("Output directory");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        createFilePanel.add(directoryLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        createFilePanel.add(directoryText, gridBagConstraints);

        browseButton.setText("Browse");
        browseButton.setMargin(new java.awt.Insets(2, 6, 2, 6));
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        createFilePanel.add(browseButton, new java.awt.GridBagConstraints());

        fileNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fileNameLabel.setText("File name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        createFilePanel.add(fileNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        createFilePanel.add(fileNameText, gridBagConstraints);

        addTimeToFileCheck.setText("Add time to file name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        createFilePanel.add(addTimeToFileCheck, gridBagConstraints);

        fileSuffixLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fileSuffixLabel.setText("File suffix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 4);
        createFilePanel.add(fileSuffixLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        createFilePanel.add(fileSuffixText, gridBagConstraints);

        utlFormatLabel.setText("Bank Utl Format");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        createFilePanel.add(utlFormatLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        createFilePanel.add(utlFormatCombo, gridBagConstraints);

        add(createFilePanel);

        readFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Read reconciliation files"));
        readFilesPanel.setLayout(new java.awt.GridBagLayout());

        defaultDirLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        defaultDirLabel.setText("Default directory ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        readFilesPanel.add(defaultDirLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        readFilesPanel.add(defaultDirText, gridBagConstraints);

        browseDefaultDirButton.setText("Browse");
        browseDefaultDirButton.setMargin(new java.awt.Insets(2, 6, 2, 6));
        browseDefaultDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseDefaultDirButtonActionPerformed(evt);
            }
        });
        readFilesPanel.add(browseDefaultDirButton, new java.awt.GridBagConstraints());

        archiveDirLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        archiveDirLabel.setText("Archive directory");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        readFilesPanel.add(archiveDirLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        readFilesPanel.add(archiveDirText, gridBagConstraints);

        browseArchiveDirButton.setText("Browse");
        browseArchiveDirButton.setMargin(new java.awt.Insets(2, 6, 2, 6));
        browseArchiveDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseArchiveDirButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        readFilesPanel.add(browseArchiveDirButton, gridBagConstraints);

        add(readFilesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed

        MLBSettings outputDir = m_settings.get(MLBSettings.LB_OUTPUT_DIR);
        String startDir = outputDir != null ? outputDir.getName() : null;
        String newDir = m_parentDialog.browseForDirectory(startDir);
        if (newDir!=null) {
            directoryText.setText(newDir);
            getForm();
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void browseDefaultDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseDefaultDirButtonActionPerformed

        MLBSettings outputDir = m_settings.get(MLBSettings.LB_RECONCILIATION_DIR);
        String startDir = outputDir != null ? outputDir.getName() : null;
        String newDir = m_parentDialog.browseForDirectory(startDir);
        if (newDir!=null) {
            defaultDirText.setText(newDir);
            getForm();
        }
    }//GEN-LAST:event_browseDefaultDirButtonActionPerformed

    private void browseArchiveDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseArchiveDirButtonActionPerformed

        MLBSettings outputDir = m_settings.get(MLBSettings.LB_RECONCILIATION_MOVETO_DIR);
        String startDir = outputDir != null ? outputDir.getName() : null;
        String newDir = m_parentDialog.browseForDirectory(startDir);
        if (newDir!=null) {
            archiveDirText.setText(newDir);
            getForm();
        }

    }//GEN-LAST:event_browseArchiveDirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addTimeToFileCheck;
    private javax.swing.JLabel archiveDirLabel;
    private javax.swing.JTextField archiveDirText;
    private javax.swing.JButton browseArchiveDirButton;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton browseDefaultDirButton;
    private javax.swing.JPanel createFilePanel;
    private javax.swing.JLabel defaultDirLabel;
    private javax.swing.JTextField defaultDirText;
    private javax.swing.JLabel directoryLabel;
    private javax.swing.JTextField directoryText;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField fileNameText;
    private javax.swing.JLabel fileSuffixLabel;
    private javax.swing.JTextField fileSuffixText;
    private javax.swing.JPanel readFilesPanel;
    private javax.swing.JComboBox utlFormatCombo;
    private javax.swing.JLabel utlFormatLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return("LB settings");
    }

    @Override
    public String getTip() {
        return("LB settings");
    }


}
